import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Hello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body      >
        <nav>
          <ul>
            <li><a href="/"></a></li>
            <li><a href="/profile">Profile</a></li>
            <li><a href="/profile">Thread</a></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
